### ISSUE TITLE
Method createObject of DomainObjectDataMapperInterface, seem to have a useless parameter $dataClass

### ISSUE THREAD

**Issue by mcsky** [biig-io/Melodiia#35]
Please [see file ](https://github.com/biig-io/Melodiia/blob/master/src/Bridge/Symfony/Form/DomainObjectDataMapperInterface.php)

I don't get what is the purpose of the `string $dataClass = null` parameter.

The data class can be retrieved directly from the `form` instance.

```php
if (!$form instanceof FormInterface) {
    return null;
}

$dataClass = $form->getConfig()->getOption('data_class');
if (MyObject::class !== $dataClass) {
   throw new InvalidArgumentException('Expected "$dataClass" to be equals to ' . MyObject::class);
}
```

Moreover the [ApiType](https://github.com/biig-io/Melodiia/blob/master/src/Bridge/Symfony/Form/Type/ApiType.php), which call `createObject` don't give a second parameter (the dataClass), so the value is always null.

**Comment by Nek-** [comment]
But the [DomainObjectsDataMapper](https://github.com/biig-io/Melodiia/blob/master/src/Bridge/Symfony/Form/DomainObjectsDataMapper.php#L15) actually does! (feel free to close)
