### ISSUE TITLE
FormErrorResponse - errors format change between two types of form

### ISSUE THREAD

**Issue by khylias** [biig-io/Melodiia#53]
The FormErrorResponse class is returning different errors format between two types of form.

First case:
I've got a form resolved by an object. Then the error format is as below : 
```javascript
{
  "violations": {
    "registration.email": [
      "Email is required"
    ],
    "registration.plainPassword": [
      "Password is required"
    ]
  }
}
```

Second case:
I've got a simple form created by a class, then the error format takes a different shape.
```javascript
{
   "violations":{
      "[currentPassword]":[
         "Given password don't match with user password"
      ]
   }
}
```
### Behavior
In basic form, error properties are named as an array adversely of an object path.

### Expected
Standardize all error properties as object paths.

**Comment by Nek-** [comment]
Hum. Considering it's tested, I guess it's an expected behavior. But why? (and modifying it is a BC break)

https://github.com/biig-io/Melodiia/blob/0c6ca3c3c6e1a5e3b938017652dec73de3006f5e/tests/Melodiia/Bridge/Symfony/Response/FormErrorResponseTest.php#L90-L104
